### ISSUE TITLE
Hello, How to judge whether CPU will bottleneck GPU?

### ISSUE THREAD

**Issue by zhangqianhui** [beopst/tf-performance-tips#1]
Can you give me some methods or linking?

**Comment by beopst** [comment]
It is easily noticed by monitoring GPU utilization. If it goes to zero (i.e. GPU is idle), it means that there is no data to process on GPU. In other words, in this case the processing (prefetching) time on CPUs are longer than that on GPUs.

**Comment by zhangqianhui** [comment]
thanks
